// <auto-generated />
using System;
using CinemaForYou.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaForYou.Migrations
{
    [DbContext(typeof(CinemaForYouDbContext))]
    partial class CinemaForYouDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaForYou.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageName = "agedeglace.jpg",
                            ImagePath = "wwwroot/img/movie/agedeglace.jpg",
                            MovieId = 6
                        },
                        new
                        {
                            Id = 2,
                            ImageName = "alien.jpg",
                            ImagePath = "wwwroot/img/movie/alien.jpg",
                            MovieId = 9
                        },
                        new
                        {
                            Id = 3,
                            ImageName = "avatar.jpg",
                            ImagePath = "wwwroot/img/movie/avatar.jpg",
                            MovieId = 8
                        },
                        new
                        {
                            Id = 4,
                            ImageName = "gremlins.jpg",
                            ImagePath = "wwwroot/img/movie/gremlins.jpg",
                            MovieId = 3
                        },
                        new
                        {
                            Id = 5,
                            ImageName = "jurassicpark.jpg",
                            ImagePath = "wwwroot/img/movie/jurassicpark.jpg",
                            MovieId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageName = "lastactionhero.jpg",
                            ImagePath = "wwwroot/img/movie/lastactionhero.jpg",
                            MovieId = 10
                        },
                        new
                        {
                            Id = 7,
                            ImageName = "massacretronconneuse.jpg",
                            ImagePath = "wwwroot/img/movie/massacretronconneuse.jpg",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 8,
                            ImageName = "nemo.jpg",
                            ImagePath = "wwwroot/img/movie/nemo.jpg",
                            MovieId = 4
                        },
                        new
                        {
                            Id = 9,
                            ImageName = "retourverslefutur.jpg",
                            ImagePath = "wwwroot/img/movie/retourverslefutur.jpg",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 10,
                            ImageName = "topgun.jpg",
                            ImagePath = "wwwroot/img/movie/topgun.jpg",
                            MovieId = 7
                        });
                });

            modelBuilder.Entity("CinemaForYou.Models.Implantation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Implantations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anvers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Namur"
                        });
                });

            modelBuilder.Entity("CinemaForYou.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("MovieTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PegiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MovieTypeId");

                    b.HasIndex("PegiId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "En 1973, lors d'une perquisition à la ferme de Thomas Hewitt, ancien employé de l'abattoir de Travis County, au Texas, la police découvrait les restes de 33 êtres humains. Cette effroyable trouvaille mit en émoi la population locale. Arborant les grotesques masques de chair de ses victimes et brandissant une tronçonneuse, le tueur fut macabrement surnommé Leatherface. Les autorités locales abattirent un homme portant un masque de cuir, mettant ainsi fin à l'affaire, mais au cours des années suivantes, plusieurs personnes accusèrent la police d'avoir bâclé l'enquête et d'avoir tué un innocent en toute connaissance de cause. Pour la première fois, la seule victime ayant survécu au massacre brise le silence et raconte ce qui est vraiment arrivé cette nuit - là, sur une route déserte du Texas, à cinq personnes qui sans le savoir, roulaient vers leur pire cauchemar.",
                            Duration = 90,
                            MovieTypeId = 3,
                            PegiId = 5,
                            ReleaseDate = new DateTime(2003, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Massacre à la tronçonneuse"
                        },
                        new
                        {
                            Id = 2,
                            Description = "1985. Le jeune Marty McFly mène une existence anonyme auprès de sa petite amie Jennifer, seulement troublée par sa famille en crise et un proviseur qui serait ravi de l'expulser du lycée. Ami de l'excentrique professeur Emmett Brown, il l'accompagne un soir tester sa nouvelle expérience : le voyage dans le temps via une DeLorean modifiée. La démonstration tourne mal : des trafiquants d'armes débarquent et assassinent le scientifique. Marty se réfugie dans la voiture et se retrouve transporté en 1955. Là, il empêche malgré lui la rencontre de ses parents, et doit tout faire pour les remettre ensemble, sous peine de ne pouvoir exister.",
                            Duration = 116,
                            MovieTypeId = 4,
                            PegiId = 2,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Retour vers le Futur"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rand Peltzer offre à son fils Billy un étrange animal : un mogwai. Son ancien propriétaire l'a bien mis en garde : il ne faut pas l'exposer à la lumiere, lui éviter tout contact avec l'eau, et surtout, surtout ne jamais le nourrir apres minuit... Sinon...",
                            Duration = 107,
                            MovieTypeId = 3,
                            PegiId = 3,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gremlins"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dans les eaux tropicales de la Grande Barrière de corail, un poisson-clown du nom de Marin mène une existence paisible avec son fils unique, Nemo. Redoutant l'océan et ses risques imprévisibles, il fait de son mieux pour protéger son fils. Comme tous les petits poissons de son âge, celui-ci rêve pourtant d'explorer les mystérieux récifs. Lorsque Nemo disparaît, Marin devient malgré lui le héros d'une quête unique et palpitante. Le pauvre papa ignore que son rejeton à écailles a été emmené jusque dans l'aquarium d'un dentiste. Marin ne s'engagera pas seul dans l'aventure : la jolie Dory, un poisson-chirurgien bleu à la mémoire défaillante et au grand coeur, va se révéler d'une aide précieuse.Les deux poissons vont affronter d'innombrables dangers, mais l'optimisme de Dory va pousser Marin à surmonter toutes ses peurs.",
                            Duration = 100,
                            MovieTypeId = 5,
                            PegiId = 1,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Le Monde de Némo"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ne pas réveiller le chat qui dort... C'est ce que le milliardaire John Hammond aurait dû se rappeler avant de se lancer dans le clonage de dinosaures. C'est à partir d'une goutte de sang absorbée par un moustique fossilisé que John Hammond et son équipe ont réussi à faire renaître une dizaine d'espèces de dinosaures. Il s'apprête maintenant avec la complicité du docteur Alan Grant, paléontologue de renom, et de son amie Ellie, à ouvrir le plus grand parc à thème du monde. Mais c'était sans compter la cupidité et la malveillance de l'informaticien Dennis Nedry, et éventuellement des dinosaures, seuls maîtres sur l'île...",
                            Duration = 128,
                            MovieTypeId = 3,
                            PegiId = 3,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park"
                        },
                        new
                        {
                            Id = 6,
                            Description = "L'histoire se déroule au début d'une ère glaciaire. Un trio peu ordinaire, composé d'un mammouth, Manny, d'un paresseux, Sid, et d'un tigre à dents de sabre, Diego, se retrouve avec un bébé humain. Ils décident de le rendre à ses parents mais l'enfant est celui du chef d'une tribu préhistorique chasseuse de tigres. Diego est chargé par son clan d'attirer Manny et Sid dans un piège pour récupérer l'enfant.",
                            Duration = 103,
                            MovieTypeId = 5,
                            PegiId = 1,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "L'age de Glace"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Jeune as du pilotage et tête brûlée d'une école réservée à l'élite de l'aéronavale US (Top Gun), Pete Mitchell, dit Maverick, tombe sous le charme d'une instructrice alors qu'il est en compétition pour le titre du meilleur pilote...",
                            Duration = 110,
                            MovieTypeId = 1,
                            PegiId = 4,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Gun"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Malgré sa paralysie, Jake Sully, un ancien marine immobilisé dans un fauteuil roulant, est resté un combattant au plus profond de son être. Il est recruté pour se rendre à des années-lumière de la Terre, sur Pandora, où de puissants groupes industriels exploitent un minerai rarissime destiné à résoudre la crise énergétique sur Terre. Parce que l'atmosphère de Pandora est toxique pour les humains, ceux-ci ont créé le Programme Avatar, qui permet à des pilotes humains de lier leur esprit à un avatar, un corps biologique commandé à distance, capable de survivre dans cette atmosphère létale. Ces avatars sont des hybrides créés génétiquement en croisant l'ADN humain avec celui des Na'vi, les autochtones de Pandora. Sous sa forme d'avatar, Jake peut de nouveau marcher. On lui confie une mission d'infiltration auprès des Na'vi, devenus un obstacle trop conséquent à l'exploitation du précieux minerai.Mais tout va changer lorsque Neytiri, une très belle Na'vi, sauve la vie de Jake...",
                            Duration = 162,
                            MovieTypeId = 4,
                            PegiId = 2,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Le vaisseau commercial Nostromo et son équipage, sept hommes et femmes, rentrent sur Terre avec une importante cargaison de minerai. Mais lors d'un arrêt forcé sur une planète déserte, l'officier Kane se fait agresser par une forme de vie inconnue, une arachnide qui étouffe son visage. Après que le docteur de bord lui retire le spécimen, l'équipage retrouve le sourire et dîne ensemble. Jusqu'à ce que Kane, pris de convulsions, voit son abdomen perforé par un corps étranger vivant, qui s'échappe dans les couloirs du vaisseau...",
                            Duration = 117,
                            MovieTypeId = 3,
                            PegiId = 5,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Alien, le huitième passager"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Grâce a un billet magique, Danny Madigan, un enfant de onze ans, peut vivre les aventures de son policier préferé, Slater, croisé des temps modernes. Ensemble ils affrontent force danger et triomphent toujours. Mais les choses se compliquent lorsque des personnes mal intentionnées s'emparent du billet magique et gagnent New York, ou le crime paie encore plus qu'au cinéma.",
                            Duration = 131,
                            MovieTypeId = 1,
                            PegiId = 3,
                            ReleaseDate = new DateTime(1985, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Last Action Hero"
                        });
                });

            modelBuilder.Entity("CinemaForYou.Models.MovieType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Horreur"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Science-Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dessin Animé"
                        });
                });

            modelBuilder.Entity("CinemaForYou.Models.Pegi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IllustrationPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pegis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Avec cette classification, le contenu du film est considéré comme adapté à toutes les classes d’âge. Le film ne doit pas comporter de sons ou d’images susceptibles d’effrayer ou de faire peur à de jeunes enfants. Les formes de violence très modérées dans un contexte comique ou enfantin sont acceptables. Le film ne doit faire entendre aucun langage grossier.",
                            IllustrationPath = "img/pegi/p3.jpg",
                            Number = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "Les contenus présentant des scènes ou sons potentiellement effrayants se retrouvent dans cette classe. Avec une classification PEGI 7 des scènes de violence très modérées (une violence implicite, non détaillée ou non réaliste) peuvent être autorisées.",
                            IllustrationPath = "img/pegi/p7.jpg",
                            Number = 7
                        },
                        new
                        {
                            Id = 3,
                            Description = "Des films montrant de la violence sous une forme plus graphique par rapport à des personnages imaginaires et/ou une violence non graphique envers des personnages à figure humaine entrent dans cette classe d’âge. Des insinuations à caractère sexuel ou des postures de type sexuelles peuvent être présentes, mais dans cette catégorie les grossièretés doivent rester légères.",
                            IllustrationPath = "img/pegi/p12.jpg",
                            Number = 12
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cette classification s’applique lorsque la représentation de la violence (ou d’un contact sexuel) atteint un niveau semblable à celui que l’on retrouverait dans la réalité. Les films classés dans la catégorie 16 peuvent contenir un langage grossier plus extrême, des jeux de hasard, ainsi qu’une consommation de tabac, d’alcool ou de drogues.",
                            IllustrationPath = "img/pegi/p16.jpg",
                            Number = 16
                        },
                        new
                        {
                            Id = 5,
                            Description = "La classification destinée aux adultes s’applique lorsque le degré de violence atteint un niveau où il rejoint une représentation de violence crue, de meurtre apparemment sans motivation ou de violence contre des personnages sans défense. La glorification des drogues illégales et les contacts sexuels explicites entrent également dans cette tranche d’âge. ",
                            IllustrationPath = "img/pegi/p18.jpg",
                            Number = 18
                        });
                });

            modelBuilder.Entity("CinemaForYou.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ShowId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CinemaForYou.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ImplantationId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImplantationId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImplantationId = 2,
                            Number = 1,
                            Seats = 12
                        },
                        new
                        {
                            Id = 2,
                            ImplantationId = 2,
                            Number = 2,
                            Seats = 12
                        },
                        new
                        {
                            Id = 3,
                            ImplantationId = 2,
                            Number = 3,
                            Seats = 8
                        },
                        new
                        {
                            Id = 4,
                            ImplantationId = 1,
                            Number = 1,
                            Seats = 14
                        },
                        new
                        {
                            Id = 5,
                            ImplantationId = 1,
                            Number = 2,
                            Seats = 12
                        },
                        new
                        {
                            Id = 6,
                            ImplantationId = 1,
                            Number = 3,
                            Seats = 12
                        },
                        new
                        {
                            Id = 7,
                            ImplantationId = 1,
                            Number = 4,
                            Seats = 8
                        });
                });

            modelBuilder.Entity("CinemaForYou.Models.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Heure")
                        .HasColumnType("time");

                    b.Property<int?>("ImplantationId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImplantationId");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 17, 30, 0, 0),
                            ImplantationId = 2,
                            MovieId = 2,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 20, 0, 0, 0),
                            ImplantationId = 2,
                            MovieId = 5,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 22, 0, 0, 0),
                            ImplantationId = 2,
                            MovieId = 3,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 20, 0, 0, 0),
                            ImplantationId = 2,
                            MovieId = 3,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 20, 0, 0, 0),
                            ImplantationId = 2,
                            MovieId = 7,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 17, 30, 0, 0),
                            ImplantationId = 2,
                            MovieId = 10,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 14, 30, 0, 0),
                            ImplantationId = 2,
                            MovieId = 6,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 14, 30, 0, 0),
                            ImplantationId = 2,
                            MovieId = 6,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 17, 30, 0, 0),
                            ImplantationId = 2,
                            MovieId = 6,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 17, 30, 0, 0),
                            ImplantationId = 2,
                            MovieId = 4,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 14, 30, 0, 0),
                            ImplantationId = 2,
                            MovieId = 4,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 20, 0, 0, 0),
                            ImplantationId = 2,
                            MovieId = 7,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 22, 0, 0, 0),
                            ImplantationId = 2,
                            MovieId = 7,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 17, 30, 0, 0),
                            ImplantationId = 1,
                            MovieId = 2,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 22, 0, 0, 0),
                            ImplantationId = 1,
                            MovieId = 1,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 20, 0, 0, 0),
                            ImplantationId = 1,
                            MovieId = 2,
                            RoomId = 6
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 22, 0, 0, 0),
                            ImplantationId = 1,
                            MovieId = 1,
                            RoomId = 6
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 22, 0, 0, 0),
                            ImplantationId = 1,
                            MovieId = 9,
                            RoomId = 7
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 17, 30, 0, 0),
                            ImplantationId = 1,
                            MovieId = 8,
                            RoomId = 7
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 14, 30, 0, 0),
                            ImplantationId = 1,
                            MovieId = 4,
                            RoomId = 7
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 17, 30, 0, 0),
                            ImplantationId = 1,
                            MovieId = 8,
                            RoomId = 6
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 14, 30, 0, 0),
                            ImplantationId = 1,
                            MovieId = 8,
                            RoomId = 6
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 20, 0, 0, 0),
                            ImplantationId = 1,
                            MovieId = 10,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 17, 30, 0, 0),
                            ImplantationId = 1,
                            MovieId = 10,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 22, 0, 0, 0),
                            ImplantationId = 1,
                            MovieId = 2,
                            RoomId = 6
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2021, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Heure = new TimeSpan(0, 14, 30, 0, 0),
                            ImplantationId = 1,
                            MovieId = 4,
                            RoomId = 4
                        });
                });

            modelBuilder.Entity("CinemaForYou.Models.Spectator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Spectators");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CinemaForYou.Models.Member", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("CinemaForYou.Models.Image", b =>
                {
                    b.HasOne("CinemaForYou.Models.Movie", "Movie")
                        .WithOne("Image")
                        .HasForeignKey("CinemaForYou.Models.Image", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaForYou.Models.Movie", b =>
                {
                    b.HasOne("CinemaForYou.Models.MovieType", "Type")
                        .WithMany("Movies")
                        .HasForeignKey("MovieTypeId");

                    b.HasOne("CinemaForYou.Models.Pegi", "Pegi")
                        .WithMany("Movies")
                        .HasForeignKey("PegiId");
                });

            modelBuilder.Entity("CinemaForYou.Models.Reservation", b =>
                {
                    b.HasOne("CinemaForYou.Models.Member", "Member")
                        .WithMany("Reservations")
                        .HasForeignKey("MemberId");

                    b.HasOne("CinemaForYou.Models.Show", "Show")
                        .WithMany("Reservations")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CinemaForYou.Models.Room", b =>
                {
                    b.HasOne("CinemaForYou.Models.Implantation", "Implantation")
                        .WithMany("Rooms")
                        .HasForeignKey("ImplantationId");
                });

            modelBuilder.Entity("CinemaForYou.Models.Show", b =>
                {
                    b.HasOne("CinemaForYou.Models.Implantation", "Implantation")
                        .WithMany("Shows")
                        .HasForeignKey("ImplantationId");

                    b.HasOne("CinemaForYou.Models.Movie", "Movie")
                        .WithMany("Shows")
                        .HasForeignKey("MovieId");

                    b.HasOne("CinemaForYou.Models.Room", "Room")
                        .WithMany("Shows")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CinemaForYou.Models.Spectator", b =>
                {
                    b.HasOne("CinemaForYou.Models.Reservation", "Reservation")
                        .WithMany("Spectators")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
